### ISSUE TITLE
Need prefetch feature

### ISSUE THREAD

**Issue by gapgag55** [jotaajunior/adonis-rabbit#11]
Hi team,

I really love your open source and, would like to request the prefetch feature to prevent CPU / RAM overloaded.

**Comment by jotaajunior** [comment]
Hello, [gapgag55](https://github.com/gapgag55)

Sorry for the delay. Don't know if this is what you meant, but it's already possible to prefetch:

```ts
import Rabbit from '@ioc:Adonis/Addons/Rabbit'

const channel = await Rabbit.getChannel();

channel.prefetch(10);
```
