### ISSUE TITLE
Missing RabbitMQ user

### ISSUE THREAD

**Issue by arzamk** [jotaajunior/adonis-rabbit#7]
❯ 2|  import Rabbit from '@ioc:Adonis/Addons/Rabbit'

im unable to import this modile in start/rabbit.ts

**Comment by jrsmarcilio** [comment]
@arzamk,  check if there is build folder in the path _node_modules/adonis-rabbit_

possible solution in https://github.com/jotaajunior/adonis-rabbit/issues/6#issuecomment-1284534306

**Comment by jotaajunior** [comment]
I believe updating your version fixes the issue:

```bash
yarn add adonis-rabbit@latest
```

**Comment by arzamk** [comment]
Thank you so much @jotaajunior the issue was resolved by running the command with @latest
